using Microsoft.Extensions.AI;

namespace Application;

public sealed class MyClient : IMyClient
{
    private readonly IChatClient _chatClient;

    public MyClient(IChatClient chatClient)
    {
        _chatClient = chatClient;
    }

    public async Task<string> AskQuestionAsync(string question, CancellationToken cancellationToken = default)
    {
        var response = await _chatClient.GetResponseAsync(question, cancellationToken: cancellationToken);

        return string.IsNullOrWhiteSpace(response.Text)
            ? "No response generated by the model."
            : response.Text;
    }
}
